import assert from 'node:assert/strict';
import { arenaRadius, arenaPressure, compareArenaStandings, SUDDEN_MIN_RADIUS, SUDDEN_SHRINK_SEC } from '../src/minigames/arena/arenaRules';
import { ARENA_R, ARENA_R_MIN, PLAYER_RADIUS, ACCEL } from '../src/minigames/arena/arenaTypes';
import { GameSession } from '../server/GameSession';
import { PlayerSession } from '../server/PlayerSession';
import { getMinigame, safetyCapSec } from '../shared/minigames';
assert.equal(arenaRadius(0,45),ARENA_R);
assert.equal(arenaRadius(45,45),ARENA_R_MIN);
assert.ok(arenaRadius(50,45)<ARENA_R_MIN);
assert.equal(arenaRadius(45+SUDDEN_SHRINK_SEC,45),SUDDEN_MIN_RADIUS);
assert.equal(arenaRadius(400,45),SUDDEN_MIN_RADIUS);
assert.ok(SUDDEN_MIN_RADIUS>PLAYER_RADIUS*3,'dimensione minima giocabile');
assert.equal(arenaPressure(-1),0);
assert.ok(arenaPressure(20)>ACCEL,'pressione crescente supera il campeggio verso il centro');
assert.ok(Number.isFinite(arenaPressure(10000)));
const base={alive:false,eliminatedAt:60,exitDistance:3.7,eliminations:0};
const a={...base,id:'a',entryOrder:0},b={...base,id:'b',entryOrder:1};
assert.deepEqual([b,a].sort(compareArenaStandings).map(p=>p.id),['a','b']);
assert.equal([a,{...b,exitDistance:3.61}].sort(compareArenaStandings)[0].id,'b');
assert.equal([a,{...b,eliminatedAt:61}].sort(compareArenaStandings)[0].id,'b');
assert.equal([a,{...b,alive:true}].sort(compareArenaStandings)[0].id,'b');
const session=new GameSession('ARENA',5,200,'host');
for(let i=0;i<5;i++) { const p=new PlayerSession(`p${i}`,`P${i}`,`t${i}`);p.attach(`s${i}`);p.characterId=['goblin','buttafuori','judoka','dottore','ciro'][i];p.ready=true;session.addPlayer(p); }
session.selectMinigame('arena');session.startGame();session.skip();session.skip();
assert.equal(session.phase,'MINIGAME_PLAYING');
const cap=safetyCapSec(getMinigame('arena')!);
assert.ok(cap>=300);
(session as unknown as {fallbackFinish():void}).fallbackFinish();
assert.ok(session.players.every(p=>p.score===0),'failsafe senza vincitori/punti inventati');
assert.equal(session.lastResults,null);
session.resetToLobby();
console.log('PASS Arena: scala normale/sudden/minima, pressione finita anti-stallo, spareggio stabile e failsafe server senza vittoria a tempo.');
